/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 robo.gltf --transform 
Files: robo.gltf [114.83KB] > C:\Users\anshu\OneDrive\Desktop\Robo\robo-transformed.glb [77.34KB] (33%)
Author: allzeronce (https://sketchfab.com/allzeronce)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-bot-bb951fb4e285427cbbf6b9241eac78cb
Title: Mini_bot
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./robo-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Cube_����������������_��������_0"].geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0.478, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
      <mesh
        geometry={nodes["Cube_��������_0"].geometry}
        material={materials.PaletteMaterial002}
        position={[0, 0.478, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
      <mesh
        geometry={nodes["Cube_����������_��_������_0"].geometry}
        material={materials.PaletteMaterial003}
        position={[0, 0.478, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/robo-transformed.glb");
